name: android

on:
  push:
    branches:
      - develop
    tags: ["v*"]
  pull_request:
    branches: [main]

jobs:
  build-android:
    runs-on: ubuntu-latest

    env:
      #ANDROID_SDK_ROOT: ${{ github.workspace }}/android-sdk
      ANDROID_HOME: ${{ github.workspace }}/android-sdk
      #ANDROID_NDK_VERSION: 26.1.10909125
      ANDROID_NDK_VERSION: 29.0.14033849
      JAVA_VERSION: "21"
      ANDROID_API_LEVEL: "34"
      GRADLE_OPTS: -Dorg.gradle.jvmargs="-Xmx4g -XX:+UseParallelGC"

    steps:
      - name: Checkout repo and submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Patch source
        run: |
          printf "\nbetaui        true\n" >> data/game.cfg
          mkdir -p android-project/app/src/main/assets
          cp -r data/*  android-project/app/src/main/assets
          ls -l android-project/app/src/main/assets
          sed -i -e 's/#ifdef HAVE_FSEEKO/#ifdef HAVE_FSEEKO_DISABLED/g' external/SDL3_mixer/external/wavpack/src/open_filename.c

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}

      - name: Install Android SDK cmdline tools
        run: |
          mkdir -p "$ANDROID_SDK_ROOT/cmdline-tools"
          curl -fsSL https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -o cmdline-tools.zip
          unzip -q cmdline-tools.zip -d "$ANDROID_SDK_ROOT/cmdline-tools"
          mv "$ANDROID_SDK_ROOT/cmdline-tools/cmdline-tools" "$ANDROID_SDK_ROOT/cmdline-tools/latest"
          yes | "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager" --licenses

      - name: Install SDK platforms, build tools, and NDK
        run: |
          "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager" \
            "platforms;android-${{ env.ANDROID_API_LEVEL }}" \
            "platform-tools" \
            "build-tools;34.0.0" \
            "ndk;${{ env.ANDROID_NDK_VERSION }}"

      - name: Set up Gradle cache
        uses: gradle/actions/setup-gradle@v3

      - name: Print SDK path
        working-directory: android-project
        run: ./gradlew -version

      - name: Verify environment
        run: |
          java -version
          echo "JAVA_HOME: $JAVA_HOME"
          echo "ANDROID_SDK_ROOT: $ANDROID_SDK_ROOT"
          echo "ANDROID_NDK_HOME: $ANDROID_NDK_HOME"

      - name: Verify Android SDK
        run: |
          ls -l "$ANDROID_SDK_ROOT"
          ls -l "$ANDROID_SDK_ROOT/cmdline-tools"
          ls -l "$ANDROID_SDK_ROOT/cmdline-tools/latest"
          ls -l "$ANDROID_SDK_ROOT/platforms"
          ls -l "$ANDROID_SDK_ROOT/ndk"

      - name: Verify Android NDK
        run: |
          ls -l "$ANDROID_NDK_HOME"
          "$ANDROID_NDK_HOME/ndk-build" --version

      - name: Clean old builds
        working-directory: android-project
        run: ./gradlew clean

      #- name: Build Debug APK
      #  working-directory: android-project
      #  run: ./gradlew assembleDebug -Pandroid.ndkVersion=${{ env.ANDROID_NDK_VERSION }}

      - name: Build Release APK (unsigned)
        working-directory: android-project
        run: ./gradlew assembleRelease -Pandroid.ndkVersion=${{ env.ANDROID_NDK_VERSION }}

      #- name: Build Release bundle(unsigned)
      #  working-directory: android-project
      #  run: ./gradlew bundleRelease -Pandroid.ndkVersion=${{ env.ANDROID_NDK_VERSION }}

      - name: Show build outputs
        working-directory: android-project
        run: |
          ls -l app/build/outputs/apk
          ls -l app/build/outputs/apk/release
          #ls -l app/build/outputs/bundle

      - name: Upload APK artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android-apks
          path: |
            android-project/app/build/outputs/apk/**/app-*.apk
            android-project/app/build/outputs/bundle/**/app-*.aab
